### ISSUE TITLE
error when run command_demo.sh

### ISSUE THREAD

**Issue by SupremeXiaoFu** [graspnet/graspnet-baseline#124]
When I run the following command

```shell
CUDA_VISIBLE_DEVICES=0 python demo.py --checkpoint_path ./checkpoint-rs.tar 
``` 
The output is 
```shell
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
-> loaded checkpoint ./checkpoint-rs.tar (epoch: 18)
CUDA kernel failed : an illegal memory access was encountered
void three_nn_kernel_wrapper(int, int, int, const float*, const float*, float*, int*) at L:72 in /home/robot/llm/graspnet-baseline/pointnet2/_ext_src/src/interpolate_gpu.cu
``` 
Has anyone encountered this issue?
My CUDA=12.1   torch=2.1.0   gpu=NVIDIA TITAN RTX(24G)

**Comment by SupremeXiaoFu** [comment]
I have fixed this problem by CUDA_LAUNCH_BLOCKING=1
```shell
CUDA_VISIBLE_DEVICES=0 CUDA_LAUNCH_BLOCKING=1 python demo.py --checkpoint_path ./checkpoint-rs.tar
```
